nerves-livebook/nerves_livebook

- README.md
The link of CircleCI budge should point to: 
https://app.circleci.com/pipelines/github/fhunleth/nerves_livebook
> fix link to the CircleCI budge

- priv/samples/sensors/bmp280.livemd
What about adding an example for Circuits I2C in BMP280 example so that the user can get familiar with Circuits I2C?
> Add code for using Circuits I2C in BMP280 example

- mix.exs
This PR fixes an application crash due to a failure to start `pigpiox` on non-`rpi` Nerves targets:
```
15:17:35.667 [info]  Application pigpiox exited: Pigpiox.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pigpiox.Port
** (EXIT) an exception was raised:
** (ErlangError) Erlang error: :enoent
:erlang.open_port({:spawn_executable, nil}, [:binary, :exit_status, {:args, ["-g", "-x", "-1"]}])
(pigpiox 0.1.2) lib/pigpiox/port.ex:21: Pigpiox.Port.init/1
(stdlib 3.14.1) gen_server.erl:417: :gen_server.init_it/2
(stdlib 3.14.1) gen_server.erl:385: :gen_server.init_it/6
(stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
> Limit pigpiox dependency to Raspberry Pi targets

- lib/nerves_livebook/github_release.ex
- priv/samples/networking/delta_firmware_update.livemd
- priv/samples/networking/firmware_update.livemd
- priv/samples/networking/penultimate_update.livemd
- test/nerves_livebook/github_release_test.exs
Once this gets in, it will require 2 releases for it to work. The reason
is that the script needs to be in the second-to-latest release so that
it can do a delta update to the latest release.
> Add Livebooks that demo delta firmware updates

- README.md
- config/config.exs
- config/provisioning.conf
- lib/nerves_livebook/application.ex
This is a way for provisioning WiFi credentials without using AP mode or requiring the user to build their own firmware.
> Add support for provisioning WiFi

- lib/nerves_livebook/application.ex
- lib/nerves_livebook/mix_install.ex
- test/nerves_livebook/mix_install_test.exs
Even though Mix.install/1 isn't supported by Nerves Livebook, we can
check that what the book installs is available and give a helpful error
message if not.
> Support books that use Mix.install/1

- config/config.exs
- config/target.exs
- lib/nerves_livebook.ex
- mix.exs
This sets up Erlang distribution so that the name is predictable and
reachible using mDNS. Currently, it is hardcoded to
`livebook@hostname.local` where `hostname` is `nerves-<board id>`.
The cookie hasn't changed from before. Code was just cleaned up in this
area.
> Setup Erlang distribution to use mDNS

- priv/samples/basics/spi_rgb_leds.livemd
Closes #33 
Adding basic example on controlling a SPI RGB LED strip like SK9822 or APA102.
This covers connecting the Nerves device to an RGB strip, blinking a single LED, a larson scanner, and a basic rainbow.
https://user-images.githubusercontent.com/59489977/129496100-ccd93472-33ea-47bb-a7e6-26089f792ea5.mp4
> feat: SPI RGB strip

- README.md
This also removes the RPi0 warning since Nerves Livebook has been run on
quite a few other boards regularly since that was written.
> Update first-time instructions

- priv/samples/networking/delta_firmware_update.livemd
- priv/samples/networking/firmware_update.livemd
- priv/samples/networking/penultimate_update.livemd
- priv/welcome.livemd
Some locations were referring to them as Livebooks. The main Livebook
example notebooks all refer to them "notebooks" so update everything to
be consistent.
> Refer to code notebooks consistently

- scripts/ci_create_firmware.sh
This is silly in production, but for demonstration, having firmware
updates around that go to the same image that you're using is really
convenient. I.e., you don't have to downgrade to the previous image to
try out the delta firmware update code again.
> Create delta firmware for updates to the same image

- config/target.exs
- lib/nerves_livebook/application.ex
- priv/welcome.livemd
This removes the "s" so that the data directory is the same as the
application name. This also is more consistent with the use of
"Livebook" to refer to the app and "notebook" or "code notebook" to
refer to the files.
This will certainly be an annoying update, but better late than never.
> Save notebooks to /data/livebook

- config/config.exs
This is fixed in Elixir 1.12 and nerves_livebook only works with Elixir
1.12.
> No need to check for empty atoms in Mix.target()

- config/target.exs
- lib/nerves_livebook.ex
When I was at NervesConf I noticed that a few people had trouble realizing that `ssh nerves.local` would not work and instead they needed to do `ssh livebook@nerves.local`. This is an attempt at fixing that (or removing the restriction completely!)
This is probably not quite how we want to do it. But there are two options for improvement and I figured I'd just show them both on one PR.
Set `:pwdfun` to control what the valid passwords are, the simplest implementation of this is to just return `true` (which is currently in this PR), this will allow an ssh connect to succeed with **ANY** username and password combo. Very easy. Also very insecure, but is it that much different than stating the correct username and password at the SSH prompt? Another way to do this would be to allow any …
> Super easy login

- priv/samples/basics/pwm.livemd
- priv/samples/basics/sys_class_leds.livemd
Hey there! I discovered a few days ago that livebook markdown doesn't support out-of-line links, and noticed a few in the PWM example today.
This corrects them, and fixes the placement of a few apostrophes in the grammar of these docs as well.
> Correct PWM links (and some apostrophes).

- priv/samples/networking/configure_wifi.livemd
IO.gets is hard deprecated.. added a select for SSIDs and minimal text changes, for improved UX.
NB: the preprended empty option: [{"", "SSIDs:"}] ++  is added as to not default connect to first/strongest network with no password, in case one evals all the code.
> use Kino.Input in configure_wifi.md + improved UX

- lib/nerves_livebook/pattern_led.ex
- lib/nerves_livebook/ui.ex
- test/nerves_livebook/pattern_led_test.exs
PWM LEDs can support many more levels of brightness so hardcoding the
brightness to 1 ends up making them pretty dim. This changes the code to
get the max_brightness and use it.
> Support LEDs with max_brightness > 1

- config/host.exs
- lib/nerves_livebook.ex
- lib/nerves_livebook/application.ex
- lib/nerves_livebook/ui.ex
- test/nerves_livebook/dependencies_test.exs
Specifically these warnings:
```
You have configured application :vintage_net in your configuration file,
but the application is not available.
This usually means one of:
1. You have not added the application as a dependency in a mix.exs file.
2. You are configuring an application that does not really exist.
Please ensure :vintage_net exists or remove the configuration.
You have configured application :nerves_time in your configuration file,
but the application is not available.
This usually means one of:
1. You have not added the application as a dependency in a mix.exs file.
2. You are configuring an application that does not really exist.
Please ensure :nerves_time exists or remove the configuration.
You have configured application :mdns_lite in your configuration file,
but the …
```
> Remove host warnings

- lib/nerves_livebook/ui.ex
All of the devices with 1 or 2 LEDs have a green or blue one to use.
At some point, we may need to choose themes based on the device.
> Switch LEDs to cyan since all-on is less nice

- .dialyzer_ignore.exs
- lib/nerves_livebook/application.ex
- lib/nerves_livebook/wifi_monitor.ex
- test/nerves_livebook/wifi_monitor_test.exs
This is currently only used for the `:srhub` target since it is critical that
a WiFi network is available being the only means of connection to this
specific hardware target. If it is deemed that the target has no way to
connect to a network, then it will start itself in AP mode to allow a user
to connect directly to the device
> Add WiFiMonitor to ensure a WiFi network is available

- .circleci/config.yml
- .tool-versions
This reports a warning when building since `nerves` is forced to an
earlier version, but this warning isn't a real problem.
> Bump Elixir to 1.14.0

- priv/samples/basics/blink.livemd
- priv/samples/basics/button.livemd
- priv/samples/basics/spi_rgb_leds.livemd
- priv/samples/networking/vintage_net.livemd
Fix broken external links like the image below:
After fixed
- As I observe how Livebook handle external links, it seems like Livebook filters out links that are not directly within the paragraphs.
> Fix broken external links

- config/srhub.exs
To match the rest of the available targets. This is confirmed to set the LEDs to green once it's on wifi.
> Update srhub config for delux indicator settings

- priv/samples/debug/diagnostics.livemd
Currently in the diagnostics notebook, we parse the `Nerves.Runtime.KV.get_all` output into a map of group name to key-value tuple list. `Kino.DataTable.new` complains about that data structure. It seems `Kino.DataTable.new` no longer accepts a key-value tuple list although I had trouble finding exactly when this breaking change happened, quickly scanning [CHANGELOG](https://github.com/livebook-dev/kino/blob/main/CHANGELOG.md).
```elixir
Mix.install([
{:kino, "~> 0.12.0"}
])
```
I added an extra step that converts all the key-value tuples to maps before rendering data tables.
- The last `|> Kino.render` should be removed because Livebook implicitly does that for us. With that, we would end up getting a duplicated table.
> fix diagnostics notebook

- mix.exs
Hi @fhunleth, `tflite_elixir` v0.3.6 (i.e., its dependency `tflite_beam` v0.3.5) now has precompiled binaries for armv6 devices!
> include tflite_elixir for armv6 devices

- lib/nerves_livebook/application.ex
When [vintage_net_wifi v0.12.4](https://github.com/nerves-networking/vintage_net_wifi/releases/tag/v0.12.4) was introduced with `VintageNetWiFi.network_configured?` at dc8c36a, the boolean output of `wlan0_unconfigured?/0` became reversed. This pull request will correct it.
Ideally, this pull request should be merged before releasing https://github.com/nerves-livebook/nerves_livebook/pull/524.
- With this change, WiFi was able to get configured based on the values such as [`NERVES_WIFI_SSID`](https://github.com/nerves-livebook/nerves_livebook?tab=readme-ov-file#firmware-provisioning-options) provided when firmware is built. (tested with rpi4)
> Fix setup_wifi/0

- priv/samples/bluetooth/ble_device_with_nerves.livemd
This PR adds an additional service to the definition in the BLE Livebook which essentially functions as a cache buster for BLE clients.
The definition for this [service ](https://bitbucket.org/bluetooth-SIG/public/src/68a8c2c953c1bdc6f450d95e757b40eafc94dbfd/assigned_numbers/uuids/service_uuids.yaml#lines-38 )and it's associated [characteristic ](https://bitbucket.org/bluetooth-SIG/public/src/68a8c2c953c1bdc6f450d95e757b40eafc94dbfd/assigned_numbers/uuids/characteristic_uuids.yaml#lines-50) are implemented as defined in the BLE spec..
Without this service, users who fork this livebook and connect to the GATT server with mobile app may find that they get unexpected and difficult to understand errors if they modify the service definition in certain ways (e.g. change the `uuid` of the custom …
> Adds gatt service to the BLE sample Livebook

- priv/samples/tflite.livemd
The "Use TensorFlow Lite on Nerves Livebook" notebook is currently not working properly.
As I did investigation, there were multiple issues such as:
- The versions of the packages [req] and [progress_bar] specified in the notebook do not match those actually installed in mix.exs
- The [req] version 4 has introduced a few breaking changes:
- changed the data structure of the headers from list to map
- deprecated the `:output` option
Here is the CHANGELOG of the req package:
- https://hexdocs.pm/req/changelog.html#v0-4-0-2023-09-01
- diff https://diff.hex.pm/diff/req/0.3.12..0.4.0
[req]: https://hex.pm/packages/req
[progress_bar]: https://hex.pm/packages/progress_bar
resolves #551
- update code in a way that supports req v4+
- relax req version in the notebook
- relax progress_bar version …
> fix: get tflite sample notebook working again

- priv/samples/tflite.livemd
fix #563
[![Run in Livebook](https://livebook.dev/badge/v1/pink.svg)](https://livebook.dev/run?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnerves-livebook%2Fnerves_livebook%2F7d6aedc6426426c233edf9d6bffadf5280d9feb7%2Fpriv%2Fsamples%2Ftflite.livemd)
- The side effect from removing what is removed here is merely the progress bar animation going away, which is no big deal.
- ~[progress_bar] package is not used anywhere else so I am removing it~
- Done adjustment for Kino breaking change at v0.11.0
[progress_bar]: https://hex.pm/packages/progress_bar
> Fix file downloader in tflite example

- config/config.exs
The github release info will be picked up by the livebook update checker and will compare the compiled nerves project with the latest version of the correct repo
See discussion in [issue/236](https://github.com/nerves-livebook/nerves_livebook/issues/236) for more info and the current limitations
> partial fix for Issue 236: Adding github release info

- README.md
Hey all 👋 
new to the fantastic world of Nerves 🤩 
Thanks for the great work, i just bought a new RPi zero 2 W and I'm enjoying blinking leds.
If I don't mistake, in [v0.11.1](https://github.com/nerves-livebook/nerves_livebook/releases/tag/v0.11.1) rpi0 2 W has been added to supported the RPi targets (64-bit mode).
The PR updates the README to list it within the support devices to match the asset name in the release.
Based on my understanding before you could use the rpi3a firmware (32bit mode).
Cheers ✌️
> Add `rpi0_2` to the list of the device to match the release asset

- lib/nerves_livebook/application.ex
- lib/nerves_livebook/mix_install.ex
This fixes:
```
Runtime terminated unexpectedly - an exception was raised:
** (UndefinedFunctionError) function Mix.install_project_dir/0 is undefined or private
Mix.install_project_dir()
(livebook 0.15.5) lib/livebook/runtime/erl_dist/runtime_server.ex:858: Livebook.Runtime.ErlDist.RuntimeServer.report_transient_state/1
(livebook 0.15.5) lib/livebook/runtime/erl_dist/runtime_server.ex:406: Livebook.Runtime.ErlDist.RuntimeServer.handle_info/2
(stdlib 6.2.1) gen_server.erl:2345: :gen_server.try_handle_info/3
(stdlib 6.2.1) gen_server.erl:2433: :gen_server.handle_msg/6
(stdlib 6.2.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```
Fixes #633
> Add stub Mix.install_project_dir to fix exception
